### ISSUE TITLE
Добрый день! Я могу к Вам обраться за консультацией по этой задаче?

### ISSUE THREAD

**Issue by Alexander-Tulenev** [heavenyoung1/VKinder_bot_VK#1]

**Comment by heavenyoung1** [comment]
добрый день, безусловно

**Comment by Alexander-Tulenev** [comment]
Подскажите, почему ссылку Вы оборачиваете в f строку?
def name(self, user_id):
"""ПОЛУЧЕНИЕ ИМЕНИ ПОЛЬЗОВАТЕЛЯ, КОТОРЫЙ НАПИСАЛ БОТУ"""
url = f' https://api.vk.com/method/users.get '
params = {'access_token': user_token,
'user_ids': user_id,
'v': '5.131'}
repl = requests.get(url, params=params)
response = repl.json()
try:
>Четверг, 2 марта 2023, 11:56 +07:00 от Eugene Mefyod ***@***.***>:
> 
> 
>добрый день, безусловно
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <heavenyoung1/VKinder_bot_VK/issues/1/1451298486 @ github . com> 
 
 
Александр Александрович Т.

**Comment by heavenyoung1** [comment]
Вопрос странный, можно конечно не использовать f-строку.

**Comment by Alexander-Tulenev** [comment]
Добрый день!
В смысле странный вопрос, в программировании странных вопросов не бывает. я только начал этим заниматься и мне никто не может объяснить зачем ссылку оборачивать в F_строку? Также я нигде не нашел этой информации в интернете...Вы можете объяснить для чего вы это делаете, что это дает?

**Comment by heavenyoung1** [comment]
"F-строки" обеспечивают краткий, читаемый способ включения значения выражений Python внутри строк. В исходном коде Python форматированная строка или по другому f-string - это буквальная строка с префиксом 'f' или 'F', которая содержит выражения внутри фигурных скобок {}. Выражения заменяются их значениями.
допустим есть переменная **x**
Мы хотим вставить эту переменную в строку, проще всего это делать при помощи f-строки;
x = 'Michael'
print(f'My name is {x}!')
>>> My name is Michael!

Для сравнения переменную можно вставить в строку и другим образом, но это будет не так красиво: пример
old = 17
print("I'm" + old + "years old")
>>> I'm 17 years old

Согласись, что использование форматированных строк (f-string) сильно упрощает работу и делает код проще.
